
# Use phusion/baseimage as starting point.
FROM phusion/baseimage:0.10.2

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

RUN apt-get update && apt-get install -y build-essential apache2 midicsv lilypond openjdk-9-jre

RUN apt-get install -y graphviz

WORKDIR /inst

ADD provconvert-0.7.3.deb .

RUN apt install ./provconvert-0.7.3.deb

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
